service: lambda-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: lamda-crud-dev 
  deploymentMethod: direct
  timeout: 30


functions:
  verify-token:
     handler: handler.verifyToken 
 
  registration:
    handler: handler.registration
    events:
      - http:
          path: /registration
          method: post
  login:
    handler: handler.login
    events:
      - http:
          path: /login
          method: post
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: /user/update
          method: post
          authorizer: verify-token

  UserById:
    handler: handler.getUserById
    events:
      - http:
          path: /user/{id}
          method: get



plugins:
  - serverless-offline
custom:
  prune:
    automatic: true
    number: 3