name: lambda-deployment-with-github-action-test

on: 
  push:
    branches:
      - main 
  
jobs:
  lambda: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          
      - name: Install serverless globally
        run: npm install -g serverless
      
      - name: Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.ACCESS_KEY }} --secret ${{ secrets.SECRET_KEY }}

      - name: Install npm dependencies
        run: npm ci
     
      - name: Deploy lambda function
        run: serverless deploy